### ISSUE TITLE
Add error codes

### ISSUE THREAD

**Issue by imdhemy** [piscibus/dolphin-api#4]
Each exception should have a unique code.
- [ ] Validation exceptions.

**Comment by imdhemy** [comment]
Hi @abdelrahman-waziry, @AmrAymanMohamed 

**I have a question about the expected response in the following scenario:**

Suppose you are sending an HTTP request to the login form for example which expects email and password, but you sent invalid data for both of them. What do you expect in a such case?

- The first matched error code.
- an Array of error codes?

**Another thing I'm thinking about:**
What is implemented now to return on errors is an array of error messages with unique keys that are matched with the requested field/input. I bet you can extract the same data without relying on error codes since you know the context (HTTP request) and the field (email, password, etc.)

**Comment by abdelrahman-waziry** [comment]
I think an array of error codes

**Comment by imdhemy** [comment]
> Another thing I'm thinking about:
What is implemented now to return on errors is an array of error messages with unique keys that are matched with the requested field/input. I bet you can extract the same data without relying on error codes since you know the context (HTTP request) and the field (email, password, etc.)

@abdelrahman-waziry
Based on this quote, there is no need for error codes!

**Comment by imdhemy** [comment]
As per our discussion, this is not going to be implemented. We'll stick to the current implementation.
@abdelrahman-waziry

**Comment by abdelrahman-waziry** [comment]
@imdhemy fair enough
